apiVersion: v1
kind: Pod
metadata:
  labels:
    app: instavote-cd
spec:

  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.11.2-4
      imagePullPolicy: Always
      command:
        - cat
      tty: true
