pipeline {

  environment {
    AUTH_TOKEN = credentials('argocd-jenkins-deployer-token')
    ARGO_SERVER = credentials('argo-server-ip')
    DEV_URL = credentials('vote-url')
  }

  agent {
    kubernetes {
      yamlFile 'redis/build-agent.yaml'
      defaultContainer 'docker-tools'
      idleMinutes 1
    }
  }

  stages {

    stage('Image Analysis') {
      parallel {
        stage('Image Linting') {
          steps {
            container('docker-tools') {
              sh "dockle docker.io/redis:alpine"
            }
          }
        }
        stage('Image Scan') {
          steps {
            container('docker-tools') {
              //sh "trivy image --exit-code 1 xvag/redis2:v62"
              sh "trivy image redis:alpine"
            }
          }
        }
      }
    }

    stage('Scan k8s Deploy Code') {
      steps {
        container('docker-tools') {
          sh 'kubesec scan redis/deployments/redis-deploy.yaml'
        }
      }
    }

    stage('Deploy to Dev') {
      steps {
        container('docker-tools') {
          sh 'docker run -t schoolofdevops/argocd-cli argocd app sync redis --insecure --server $ARGO_SERVER --auth-token $AUTH_TOKEN'
          sh 'docker run -t schoolofdevops/argocd-cli argocd app wait redis --health --timeout 300 --insecure --server $ARGO_SERVER --auth-token $AUTH_TOKEN'
        }
      }
    }

  }
}
